### ISSUE TITLE
Template is unlicensed

### ISSUE THREAD

**Issue by jonas080301** [viandwi24/nuxt3-awesome-starter#1]
Hi there,

I would love to use this template for my website.
Unfortunately, there is no license. 
Would you be so kind and add one :)

Thank you in advance

**Comment by viandwi24** [comment]
Sorry for the delay, because initially this template was just a fad and still in the process of improvisation.

I have added an MIT license which can be checked in the [following reference](https://github.com/viandwi24/nuxt3-awesome-starter/commit/4bc1b1f01c703899eca21ac162f21a776d006776).

Thank you and have a nice day!

**Comment by jonas080301** [comment]
> Sorry for the delay, because initially this template was just a fad and still in the process of improvisation.
> 
> I have added an MIT license which can be checked in the [following reference](https://github.com/viandwi24/nuxt3-awesome-starter/commit/4bc1b1f01c703899eca21ac162f21a776d006776).
> 
> Thank you and have a nice day!

Wow thank you so much for your fast response.
Keep up your great work!
