### ISSUE TITLE
VueUse

### ISSUE THREAD

**Issue by VidarDev** [viandwi24/nuxt3-awesome-starter#4]
Hi i didnt know why this is red marked

![Wr8L9hv](https://user-images.githubusercontent.com/98586665/156887426-346d25c6-db69-4b2e-aab4-a95c62bf9418.png)
.

**Comment by VidarDev** [comment]
And where i can find this svg to edit?

![Wr8L9hv](https://user-images.githubusercontent.com/98586665/156887656-86f0a55b-6e3f-4bfc-b3c8-809ab3d97a36.png)

**Comment by viandwi24** [comment]
in the first problem, this is because the nuxt config is written using typescript, when installing the module/library we need to declare types for that config, here as an example of vue use, I have declared this types config for VueUse in `tsconfig.json`

```json
{
  // https://v3.nuxtjs.org/concepts/typescript
  "extends": "./.nuxt/tsconfig.json",
  "compilerOptions": {
    "types": [
      "nuxt-windicss",
      "@vueuse/nuxt",    <====== VUEUSE TYPES
      "@intlify/nuxt3"
    ]
  }
}
```

you just run the command `yarn dev` and let nuxt generate automatically for all types, so error types like above will disappear after running dev for the first time.

**Comment by viandwi24** [comment]
then in your second problem, it's the navbar icon.

you can find it in component `builder/navbar`

is on this line:

https://github.com/viandwi24/nuxt3-awesome-starter/blob/5cff9e6391d4233eca3bb99b6299d4fffe93d839/components/Builder/Navbar.vue#L40

**Comment by viandwi24** [comment]
hope it helps, good luck.
