### ISSUE TITLE
Vscode bug on pages

### ISSUE THREAD

**Issue by florealcab** [viandwi24/nuxt3-awesome-starter#49]
On pages inside a subfolder of pages folder (example: pages/post/index.vue) I have a bug with VScode: it says composables functions are not defined, and an error with the import, see the image below:
![image](https://user-images.githubusercontent.com/16965090/210434144-1b33df2c-4e09-4507-a1ed-b29347c56371.png)

Do you have the same problem? It's a problem I have with my project too, and I didn't find a fix :/

**Comment by viandwi24** [comment]
have you run the program using "pnpm dev"?

**Comment by viandwi24** [comment]
have you run the program using "pnpm dev"?

**Comment by florealcab** [comment]
I didn't, so I run in console then the bug disapears :o

But why? I have another project I installed with yarn and "yarn dev" did not fix that bug. Do you add something in this app cause pnpm dev fix the issue, or it's just pnpm?

**Comment by florealcab** [comment]
Oh ah no, if I do yarn dev, then reopen vscode it works again... seems to be a nuxt strange issue so I can close

**Comment by viandwi24** [comment]
as I wrote in the readme,

this project was created using pnpm, because pnpm has a different working concept than yarn and npm so it might cause problems if not using pnpm in projects that use pnpm.

**Comment by viandwi24** [comment]
and this is actually a type problem.

nuxt typescript of course uses the types definition, and it will only be generated when you have run the program using "pnpm dev" because of our need for development.

the dev command will run nuxt and automatically generate types in the ".nuxt" folder.

if this folder does not exist, then this project will certainly display error problems, namely types are not defined in various functions.

**Comment by viandwi24** [comment]
or you can use "npx nuxi prepare" for only generate types. 
![image](https://user-images.githubusercontent.com/41994283/210658089-2e710aaa-4bcb-4547-8ba7-142dc172edd6.png)
