### ISSUE TITLE
Question about dependencies

### ISSUE THREAD

**Issue by HugoRCD** [viandwi24/nuxt3-awesome-starter#50]
Just a simple question why did you put all the dependencies in devdependence ?

**Comment by viandwi24** [comment]
I don't really understand, but I followed from the nuxt starter template. Some of the reasons behind this might be:


1. almost all dependencies are needed during the dev period (before being built in production)

2. front end like nuxt was created to be independent, once it's been built we don't need the dependencies needed.

so from the reasons above, I conclude to put dependencies into dev, because during production, the deploy process does not require dependencies to be installed, it only needs to run the build results in the .output folder

maybe that's from me, if there are other inputs are welcome.
