### ISSUE TITLE
vscode setup

### ISSUE THREAD

**Issue by laportem** [viandwi24/nuxt3-awesome-starter#6]
Can you share or explain your vscode setup because I am getting lots of Unknown at rule @apply scss(unknownAtRules) in .vue files

**Comment by viandwi24** [comment]
@apply is a feature of tailwind, which can be seen here "https://tailwindcss.com/docs/functions-and-directives#apply"
this is because scss does not detect the rule or directive from @apply.

but i have considered not using @apply then, i have updated in my new commit 08947b8fc94c9f755870248ee4eab20e59be0204

**Comment by ironytr** [comment]
> @apply is a feature of tailwind, which can be seen here "https://tailwindcss.com/docs/functions-and-directives#apply" this is because scss does not detect the rule or directive from @apply.
> 
> but i have considered not using @apply then, i have updated in my new commit [08947b8](https://github.com/viandwi24/nuxt3-awesome-starter/commit/08947b8fc94c9f755870248ee4eab20e59be0204)

hey man, its out of this topic but, this husky or lint thing is deleted whole my project revert back to template state, in inside im deeply crying becuz all files gone T_T and i was dumb to delete .git folder before i notice my files gone. i lost completely my project. I wish that lint or husky which thing is caused this damage to me wasn't added to project :((
