### ISSUE TITLE
Question: why are pages in different folders?

### ISSUE THREAD

**Issue by pastebimas** [viandwi24/nuxt3-awesome-starter#70]
Hello,
I'm BE developer and new to nuxt & SPA. 
Thank you for the example project, everything looks great except I can't understand:
1. why there are /pages and /app/pages folders? What is the purpose of having them separately ?
2. /stores and /app/stores.  They have duplicated use-counter. I've even removed it from /stores and the example still works.  

Thanks

**Comment by viandwi24** [comment]
hello @pastebimas, I have just integrated this project with the Nuxt Layer feature. this feature make this project can extend to your project very easily.
but the problem is, i just want this project just skeleton and collection of components, this is why im separate to folder "/app", this folder is for documentation web, like if you see at "https://nuxt3-awesome-starter.vercel.app/".

so for everyone want to extend this project only for use our components, they can jsut ignored folder "/app", because everything on folder "/app" only for me to build a documentation web.

btw, this folder like ".demo" folder if you know.

I hope this helps explain why there are /app and .demo folders, if you have any more questions about this, im feel free to answer :)

enjoy
