### ISSUE TITLE
Using extendBuild in Nuxt 3 has no effect. 

### ISSUE THREAD

**Issue by laportem** [viandwi24/nuxt3-awesome-starter#8]
I keep getting this warn on ```yarn dev```. How do one get rid of it
 
WARN  [kit] [compat] Using extendBuild in Nuxt 3 has no effect. Instead call extendWebpackConfig and extendViteConfig.

**Comment by viandwi24** [comment]
since the nuxt3 update a few days ago, there have been changes in the nuxt-kit, one of which is the use of deprecated "extendBuild". so some existing modules will experience the warning, such as the "@nuxtjs/eslint-module" module.

but during testing, I still didn't find any serious problems, so for now it can be ignored until there is an update from the module / plugin.

**Comment by lewebsimple** [comment]
See https://github.com/antfu/unplugin-icons/issues/198
